Add locking Align scripts Update help

diff --git a/sqs-add b/sqs-add
--- a/sqs-add
+++ b/sqs-add
@@ -21,6 +21,15 @@
 #                                                                              #
 ################################################################################
 
+################################################################################
+#                                                                              #
+# Helper script for the SQS                                                    #
+# Add a task to the specified queue                                            #
+#                                                                              #
+# 1 = queue                                                                    #
+#                                                                              #
+################################################################################
+
 progname=${0%-*}
 progdir=${progname%/*}
 progbase=${progname#${progdir}}
@@ -33,13 +42,17 @@ function print_help()
   # print help about this command
   cat <<EOF
 NAME
-       ${0##*/} - adds a task to a queue.
+       sqs-add - adds a task to a queue.
 
 SYNOPSIS
-       ${0##*/} QUEUE TASK
+       sqs add QUEUE TASK
 
 DESCRIPTION
        Adds task TASK to the given queue QUEUE.
+
+OPTIONS
+       -h, --help
+           Print this help and exit.
 
    Exit status
        0  if OK,
@@ -92,17 +105,26 @@ if [ ! -d ${vardir} ] ; then
   abort "sqs-add: cannot access vardir '${vardir}'"
 fi
 
-if [ ! -d ${vardir}/${queue} ] ; then
+queuedir=${vardir}/${queue}
+
+if [ ! -d ${queuedir} ] ; then
   abort "sqs-add: queue '${queue}' does not exist"
 fi
 
 key=$(hostname).$$
-sqsguard lock ${vardir}/${queue} $key
+sqsguard lock ${queuedir} $key || abort "sqs-add: cannot lock queue ${queue}"
 
-i=$(cat ${vardir}/${queue}/info/ntask)
+i=$(cat ${queuedir}/info/ntask)
 ((i++))
-echo "sqs-add: add task ${i} to queue '${queue}': '${task}'"
+info "sqs-add: add task ${i} to queue '${queue}': '${task}'"
 echo ${task} > ${vardir}/${queue}/wait/${i}
 echo ${i}    > ${vardir}/${queue}/info/ntask
 
-sqsguard unlock ${vardir}/${queue} ${key}
+sqsguard unlock ${vardir}/${queue} ${key} || "sqs-add: cannot unlock queue ${queue}"
+
+# spawn runners
+sqsdispatch ${queuedir} &
+
+exit ${E_SUCCESS}
+
+### EOF
diff --git a/sqs-close b/sqs-close
--- a/sqs-close
+++ b/sqs-close
@@ -33,13 +33,17 @@ function print_help()
   # print help about this command
   cat <<EOF
 NAME
-       ${0##*/} - <short description>
+       sqs-close - Close a queue.
 
 SYNOPSIS
-       ${0##*/} [OPTION]... [ARGUMENT]...
+       sqs close [OPTION]... [QUEUE]
 
 DESCRIPTION
-       Closes (i.e. removes) the given queue.
+       Closes (i.e. removes) the given queue QUEUE.
+
+OPTIONS
+       -h, --help
+           Print this help and exit.
 
    Exit status
        0  if OK,
@@ -74,39 +78,37 @@ until [ -z "${1}" ] ; do
       abort "Unknown option '${1}'"
       ;;
     *)
-      queue=${1%/}
+      queue=${1}
       ;;
   esac
   shift
 done
 
 ###############################################################################
-if [ -z ${queue} ] ; then
+if [ -z "${queue}" ] ; then
   abort "sqs-close: no queue given"
 fi
 
+if [ ! -d ${vardir} ] ; then
+  abort "sqs-start: cannot access vardir '${vardir}'"
+fi
+
 key="$(hostname).$$"
+sqsguard lock ${vardir} ${key} || abort "sqs-close: cannot lock '${vardir}'"
 
 queuedir=${vardir}/${queue}
-parent=${queuedir%/*}
 
-if ! [ -e ${queuedir} ] ; then
-  debug "sqs-close: path '${queuedir}' does not exist"
+if [ ! -d ${queuedir} ] ; then
   abort "sqs-close: queue '${queue}' does not exist"
 fi
 
-if ! [ -d ${queuedir} ] ; then
-  debug "sqs-close: path '${queuedir}' does not point to a directory"
-  abort "sqs-close: queue '${queue}' does not exist"
-fi
 
-sqsguard lock ${parent} ${key} || abort "sqs-close: cannot lock '${parent}'"
+sqsguard lock ${queuedir} ${key} || { sqsguard unlock ${vardir} ${key} ; abort "sqs-close: cannot lock '${queuedir}'" ; }
 
-sqsguard lock ${queuedir} ${key} || { sqsguard unlock ${parent} ${key} ; abort "sqs-close: cannot lock '${queuedir}'" ; }
-
+# check whether queue is on halt? processes running?
 rm -rf ${queuedir}
 
-sqsguard unlock ${parent} ${key} || abort "sqs-close: cannot unlock '${parent}'"
+sqsguard unlock ${vardir} ${key} || abort "sqs-close: cannot unlock '${vardir}'"
 
 exit ${E_SUCCESS}
 
diff --git a/sqs-init b/sqs-init
--- a/sqs-init
+++ b/sqs-init
@@ -26,21 +26,14 @@
 # Helper script for the SQS                                                    #
 # Initializes a new queue directory.                                           #
 #                                                                              #
-# WARNING: script does not lock <vardir>! Locking and release of the           #
-#          directory containing the queues has to be done by the caller!       #
-#                                                                              #
 # Parameters:                                                                  #
 # 1 = name of the queue                                                        #
 #                                                                              #
 # Returns                                                                      #
 #  0  on success                                                               #
-#  1  if queue already exists                                                  #
-# -1  on failure                                                               #
+#  1  on failure                                                               #
 #                                                                              #
 ################################################################################
-
-# sqs-init specific error code
-E_EXISTS=-1
 
 progname=${0}
 progdir=${progname%/*}
@@ -54,17 +47,17 @@ function print_help()
   # print help about this command
   cat <<EOF
 NAME
-       ${0##*/} - <short description>
+       sqs-init - Initialize a queue.
 
 SYNOPSIS
-       ${0##*/} [OPTION]... [ARGUMENT]...
+       sqs init [OPTION]... [QUEUE]
 
 DESCRIPTION
-       Initialize a SQS queue. Queues are created in the configured directory.
-       You can query this by calling 'sqs config get vardir .'
+       Initialize queue QUEUE. Queues are created in the configured directory.
 
-       WARNING: The script does not lock the queue directory! Concurrent
-                access to the queue directory is risky then!
+OPTIONS
+       -h, --help
+           Print this help and exit.
 
    Exit status
        0  if OK,
@@ -96,10 +89,11 @@ until [ -z "${1}" ] ; do
       exit
       ;;
     -*)
-      abort "sqs-init: unknown option '${1}'"
+      abort "Unknown option '${1}'"
       ;;
     *)
       queue=${1}
+      ;;
   esac
   shift
 done
@@ -109,41 +103,43 @@ if [ -z "${queue}" ] ; then
   abort "sqs-init: no queue given!"
 fi
 
-if [ "x${vardir}" == "x." ] ; then
-  abort "sqs-init: no vardir!"
+if [ ! -d ${vardir} ] ; then
+  abort "sqs-init: cannot access vardir '${vardir}'"
 fi
 
-# checking whether queue already exists
-if [ -e "${vardir}/${queue}" ] ; then
-  if [ "x${verbose}" = "xyes" ] ; then
-    echo "sqs-init: queue '${queue}' already exists!"
-  fi
-  exit ${E_EXISTS}
+key="$(hostname).$$"
+sqsguard lock ${vardir} ${key} || abort "sqs-start: cannot lock '${vardir}'"
+
+queuedir=${vardir}/${queue}
+
+if [ -e ${queuedir} ] ; then
+  abort "sqs-init: queue '${queue}' already exists!"
 fi
 
-# creating queue if non-existent
-if [ "x${verbose}" = "xyes" ] ; then
-  echo "sqs-init: queue does not exist, creating new queue!"
-fi
-
-mkdir ${vardir}/${queue} || exit ${E_FAILURE}
+mkdir ${queuedir} || exit ${E_FAILURE}
 
 # creating subfolders
-mkdir ${vardir}/${queue}/wait || exit ${E_FAILURE}
-mkdir ${vardir}/${queue}/exec || exit ${E_FAILURE}
-mkdir ${vardir}/${queue}/proc || exit ${E_FAILURE}
-mkdir ${vardir}/${queue}/info || exit ${E_FAILURE}
+mkdir ${queuedir}/wait || exit ${E_FAILURE}
+mkdir ${queuedir}/exec || exit ${E_FAILURE}
+mkdir ${queuedir}/proc || exit ${E_FAILURE}
+mkdir ${queuedir}/info || exit ${E_FAILURE}
 
 # creating info files
-touch ${vardir}/${queue}/info/hosts  || exit ${E_FAILURE}
-touch ${vardir}/${queue}/info/nproc  || exit ${E_FAILURE}
-touch ${vardir}/${queue}/info/nice   || exit ${E_FAILURE}
-touch ${vardir}/${queue}/info/ionice || exit ${E_FAILURE}
+touch ${queuedir}/info/hosts  || exit ${E_FAILURE}
+touch ${queuedir}/info/nproc  || exit ${E_FAILURE}
+touch ${queuedir}/info/nice   || exit ${E_FAILURE}
+touch ${queuedir}/info/ionice || exit ${E_FAILURE}
 
 # filling in default values
-echo "-1"                 > ${vardir}/${queue}/info/ntask
-echo "master=$(hostname)" > ${vardir}/${queue}/info/options
-echo "halt"               > ${vardir}/${queue}/info/state
-echo "melete:8"           > ${vardir}/${queue}/info/nproc
+echo "-1"                 > ${queuedir}/info/ntask
+echo "master=$(hostname)" > ${queuedir}/info/options
+echo "halt"               > ${queuedir}/info/state
+echo "melete:8"           > ${queuedir}/info/nproc
+
+sqsguard unlock ${vardir} ${key} || abort "sqs-init: cannot unlock '${vardir}'"
+
+info "sqs-init: created queue ${queue}"
 
 exit ${E_SUCCESS}
+
+### EOF
diff --git a/sqs-start b/sqs-start
--- a/sqs-start
+++ b/sqs-start
@@ -26,9 +26,6 @@
 # Helper script for the SQS                                                    #
 # Starts the processing of the specified queue                                 #
 #                                                                              #
-# WARNING: script does not lock <queue>! Locking and release of the            #
-#          queue has to be done by the caller!                                 #
-#                                                                              #
 # 1 = queue                                                                    #
 #                                                                              #
 ################################################################################
@@ -45,15 +42,17 @@ function print_help()
   # print help about this command
   cat <<EOF
 NAME
-       ${0##*/} - <short description>
+       sqs-start - Start processing of a queue.
 
 SYNOPSIS
-       ${0##*/} [OPTION]... [ARGUMENT]...
+       sqs start [OPTION]... [QUEUE]
 
 DESCRIPTION
-       Starts the processing of the specified queue
-       WARNING: script does not lock <queue>! Locking and release of the
-                queue has to be done by the caller!
+       Starts the processing of the given queue QUEUE.
+
+OPTIONS
+       -h, --help
+           Print this help and exit.
 
    Exit status
        0  if OK,
@@ -95,17 +94,26 @@ until [ -z "${1}" ] ; do
 done
 
 ###############################################################################
-if [ -z ${queue} ] ; then
+if [ -z "${queue}" ] ; then
   abort "sqs-start: no queue given"
+fi
+
+if [ ! -d ${vardir} ] ; then
+  abort "sqs-start: cannot access vardir '${vardir}'"
 fi
 
 queuedir=${vardir}/${queue}
 
 if [ ! -d ${queuedir} ] ; then
-  abort "sqs-start: Error, invalid queue '${queue}'"
+  abort "sqs-start: queue '${queue}' does not exist"
 fi
 
+key="$(hostname).$$"
+sqsguard lock ${queuedir} ${key} || abort "sqs-start: cannot lock queue ${queue}"
+
 echo 'run' > ${queuedir}/info/state
+
+sqsguard unlock ${queuedir} ${key} || abort "sqs-start: cannot unlock queue ${queue}"
 
 # spawn runners
 sqsdispatch ${queuedir} &
diff --git a/sqs-stop b/sqs-stop
--- a/sqs-stop
+++ b/sqs-stop
@@ -26,9 +26,6 @@
 # Helper script for the SQS                                                    #
 # Stops the processing of the specified queue                                  #
 #                                                                              #
-# WARNING: script does not lock <queue>! Locking and release of the            #
-#          queue has to be done by the caller!                                 #
-#                                                                              #
 # 1 = queue                                                                    #
 #                                                                              #
 ################################################################################
@@ -45,15 +42,17 @@ function print_help()
   # print help about this command
   cat <<EOF
 NAME
-       ${0##*/} - <short description>
+       sqs-stop - Stop processing of a queue.
 
 SYNOPSIS
-       ${0##*/} [OPTION]... [ARGUMENT]...
+       sqs stop [OPTION]... [QUEUE]
 
 DESCRIPTION
-       Stops the processing of the specified queue
-       WARNING: script does not lock <queue>! Locking and release of the
-                queue has to be done by the caller!
+       Stops the processing of the given queue QUEUE.
+
+OPTIONS
+       -h, --help
+           Print this help and exit.
 
    Exit status
        0  if OK,
@@ -95,17 +94,27 @@ until [ -z "${1}" ] ; do
 done
 
 ###############################################################################
-if [ -z ${queue} ] ; then
+if [ -z "${queue}" ] ; then
   abort "sqs-stop: no queue given"
+fi
+
+if [ ! -d ${vardir} ] ; then
+  abort "sqs-stop: cannot access vardir '${vardir}'"
 fi
 
 queuedir=${vardir}/${queue}
 
 if [ ! -d ${queuedir} ] ; then
-  abort "sqs-stop: Error, invalid queue '${queue}'"
+  abort "sqs-stop: queue '${queue}' does not exist"
 fi
 
+key="$(hostname).$$"
+sqsguard lock ${queuedir} ${key} || abort "sqs-stop: cannot lock queue ${queue}"
+
 echo 'halt' > ${queuedir}/info/state
+
+sqsguard unlock ${queuedir} ${key} || abort "sqs-stop: cannot unlock queue ${queue}"
+
 # TODO: Force flag? -> Send terminate signal to runners?
 
 exit ${E_SUCCESS}
