Merged changes into split files of sqsadmin

diff --git a/sqsadmin_settings b/sqsadmin_settings
--- a/sqsadmin_settings
+++ b/sqsadmin_settings
@@ -7,8 +7,60 @@ sqs_get() {
 
 #_______________________________________________________________________________
 sqs_set() {
-  # Set options for queue
+  # Set value in file for given host in queue to specified value
+  # The file is most likely one of (nproc|nice|ionice), however
+  # this is not limited to this. It can be any file located in 
+  # the info folder of the queue
   #
+  if [ $# -ne 4 ] ; then
+    echo "sqsadmin: Error, wrong argument count!"
+    return
+  fi
 
+  local queue=${1}
+  local host=${2}
+  local file=${3}
+  local new=${4}
+
+  if [ "x${queue}" = "x" ] ; then
+    echo "sqsadmin: Error, specify queue!"
+    return
+  fi
+
+  if [ ! -e ${vardir}/${queue} ] ; then
+    echo "sqsadmin: Error, queue '${queue}' does not exist!"
+    return
+  fi
+  
+  if ! grep ${host} ${vardir}/${queue}/info/hosts >/dev/null 2>&1 ; then
+    echo "sqsadmin: Error, no host '${host}' in queue '${queue}'!"
+    return
+  fi
+    
+  if [ ! -e ${vardir}/${queue}/info/${file} ] ; then
+    echo "sqsadmin: Error, file '${file}' does not exist in queue '${queue}'!"
+    return
+  fi
+  
+  # readout old value
+  local old=$(grep ${host} ${vardir}/${queue}/info/${file})
+  old=${old/${host}:/}
+
+  if [ "${old}" = "${new}" ] ; then
+    echo "sqsadmin: Leaving value for ${host} unchanged ('${old}')."
+    return
+  fi
+  
+  # set new value
+  sqslock ${vardir}/${queue} "root"
+  sqsset ${vardir}/${queue}/info/${file} ${host} ${new}
+  local ec=$?
+  sqsunlock ${vardir}/${queue} "root"
+
+  if [ ${ec} -eq 0 ] ; then
+    echo "sqsadmin: Changed value in ${file} for ${host} from '${old}' to '${new}'."
+  else
+    echo "sqsadmin: Error, set failed!"
+  fi
 } # sqs_set
 
